# General GitHub Repository Settings
repository:
  license: MIT

# MATLAB Toolbox Settings
matlab_toolbox:
  namespace_name: sysutil
  toolbox_name: System Utility Toolbox
  author_name: Eivind Hennestad
  author_email: 
  author_company: 
  toolbox_summary: A set of system utilities for MATLAB
  toolbox_description: |
    A set of system utilities for MATLAB. The goal is to be cross platform compatible and return MATLAB objects
  dependencies:                                     # Required MATLAB products
    - MATLAB

# Publishing options
codecov:
  badge_token: null

fileexchange:
  fex_url: null
